name: nextcloud-aio

volumes:
    nextcloud_aio_mastercontainer:
        name: nextcloud_aio_mastercontainer

services:
    nextcloud-aio-mastercontainer:
        image: nextcloud/all-in-one:latest
        init: true
        restart: unless-stopped
        container_name: nextcloud-aio-mastercontainer
        volumes:
            - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 8080:8080
        environment:
            APACHE_PORT: 11000
            APACHE_IP_BINDING: 0.0.0.0
            NEXTCLOUD_DATADIR: /mnt/970EVO_nvme0n1/Nextcloud/Data
            NEXTCLOUD_MEMORY_LIMIT: 4096M
