name: backup-encrypter

networks:
    backup-encrypter:
        name: backup-encrypter
        driver: bridge

services:
    backup-encrypter:
        container_name: Backup-Encrypter
        build: .
        image: backup-encrypter
        command: |
            sh -c
            "
            chmod 0644 /etc/cron.d/cronjob &&
            crontab /etc/cron.d/cronjob &&
            touch /var/log/cron.log &&
            cron &&
            tail -f /var/log/cron.log
            "
        working_dir: /app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./cronjob:/etc/cron.d/cronjob
            - ./.env:/app/.env
            - ./encrypt:/app/encrypt
            - ./main.sh:/app/main.sh
            - ./gitlab.sh:/app/gitlab.sh
            - ./hedgedoc.sh:/app/hedgedoc.sh
            - ${ONEDRIVE_CLIENT_DIR}:/app/syncdir
            - ${GITLAB_CONFIG_DIR}:/app/gitlab/config
            - ${GITLAB_BACKUPS_DIR}:/app/gitlab/backups
        restart: unless-stopped
