name: twitch-channel-points-miner

services:
    twitch-channel-points-miner:
        container_name: Twitch-Channel-Points-Miner
        build: .
        stdin_open: true
        tty: true
        environment:
            - TERM=xterm-256color
        volumes:
            - ./analytics:/usr/src/app/analytics
            - ./cookies:/usr/src/app/cookies
            - ./logs:/usr/src/app/logs
            - ./run.py:/usr/src/app/run.py:ro
        restart: unless-stopped
        ports:
            - "5000:5000"
